"""Add notifications table

Revision ID: f0ed24529efa
Revises: 0001_initial_schema
Create Date: 2026-08-18 19:29:23.482512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0ed24529efa'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_reference_id'), 'notifications', ['reference_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_column('audit_logs', 'updated_at')
    op.drop_index(op.f('ix_favorite_collections_created_at'), table_name='favorite_collections')
    op.drop_index(op.f('ix_favorites_created_at'), table_name='favorites')
    op.drop_column('favorites', 'updated_at')
    op.drop_index(op.f('ix_languages_created_at'), table_name='languages')
    op.drop_column('languages', 'updated_at')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_column('reports', 'updated_at')
    op.drop_index(op.f('ix_settings_created_at'), table_name='settings')
    op.drop_column('settings', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_settings_created_at'), 'settings', ['created_at'], unique=False)
    op.add_column('reports', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.add_column('languages', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_languages_created_at'), 'languages', ['created_at'], unique=False)
    op.add_column('favorites', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_favorites_created_at'), 'favorites', ['created_at'], unique=False)
    op.create_index(op.f('ix_favorite_collections_created_at'), 'favorite_collections', ['created_at'], unique=False)
    op.add_column('audit_logs', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reference_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
